#!/usr/bin/env bash

set -e # Exit on error
set -o xtrace

gjslint \
  --strict \
  --max_line_length 200 \
  --nojsdoc \
  --exclude_directories node_modules third_party \
  --recurse . \
  *.js

jshint *.js
