#!/usr/bin/env bash

mkdir -p third_party

npm install mocha
if [[ $(diff --new-file node_modules/mocha/mocha.js third_party/mocha.js) ]]; then
  echo "updating mocha.js"
  cp node_modules/mocha/mocha.js third_party/mocha.js
fi
if [[ $(diff --new-file node_modules/mocha/mocha.css third_party/mocha.css) ]]; then
  echo "updating mocha.css"
  cp node_modules/mocha/mocha.css third_party/mocha.css
fi

npm install should
if [[ $(diff --new-file node_modules/should/should.js third_party/should.js) ]]; then
  echo "updating should.js"
  cp node_modules/should/should.js third_party/should.js
fi

npm install requirejs
if [[ $(diff --new-file node_modules/requirejs/require.js third_party/require.js) ]]; then
  echo "updating require.js"
  cp node_modules/requirejs/require.js third_party/require.js
fi
